-- =====================================================
-- Migration: Create Vision Trading Agent Tables
-- Created: 2025-11-25
-- Description: Tables for Vision Agent video processing and settings
-- =====================================================

-- Table: vision_agent_videos
-- Purpose: Track YouTube videos processed by the Vision Agent
CREATE TABLE IF NOT EXISTS public.vision_agent_videos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  video_id TEXT NOT NULL,
  youtube_url TEXT NOT NULL,
  title TEXT,
  channel TEXT,
  status TEXT CHECK (status IN ('pending', 'processing', 'completed', 'failed')) DEFAULT 'pending',
  total_frames INT,
  processed_frames INT DEFAULT 0,
  signals_generated INT DEFAULT 0,
  model_version TEXT,
  processing_started_at TIMESTAMP WITH TIME ZONE,
  processing_completed_at TIMESTAMP WITH TIME ZONE,
  error_message TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Indexes for vision_agent_videos
CREATE INDEX IF NOT EXISTS idx_vision_agent_videos_user_id ON public.vision_agent_videos(user_id);
CREATE INDEX IF NOT EXISTS idx_vision_agent_videos_status ON public.vision_agent_videos(status);
CREATE INDEX IF NOT EXISTS idx_vision_agent_videos_video_id ON public.vision_agent_videos(video_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_vision_agent_videos_user_video ON public.vision_agent_videos(user_id, video_id);

-- RLS Policies for vision_agent_videos
ALTER TABLE public.vision_agent_videos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own videos"
ON public.vision_agent_videos FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own videos"
ON public.vision_agent_videos FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own videos"
ON public.vision_agent_videos FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own videos"
ON public.vision_agent_videos FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- Table: vision_agent_settings
-- Purpose: Store Vision Agent configuration for each user
CREATE TABLE IF NOT EXISTS public.vision_agent_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  enabled BOOLEAN DEFAULT false,
  mode TEXT CHECK (mode IN ('SHADOW', 'PAPER', 'LIVE')) DEFAULT 'SHADOW',
  confidence_threshold NUMERIC(3,2) DEFAULT 0.70,
  youtube_playlist_url TEXT,
  youtube_channel_url TEXT,
  model_version TEXT DEFAULT 'model_seq_v20251125.h5',
  auto_process_new_videos BOOLEAN DEFAULT false,
  max_signals_per_day INT DEFAULT 50,
  min_video_duration_seconds INT DEFAULT 60,
  max_video_duration_seconds INT DEFAULT 3600,
  frame_step INT DEFAULT 5,
  sequence_length INT DEFAULT 30,
  api_token TEXT,
  settings_json JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Indexes for vision_agent_settings
CREATE INDEX IF NOT EXISTS idx_vision_agent_settings_user_id ON public.vision_agent_settings(user_id);
CREATE INDEX IF NOT EXISTS idx_vision_agent_settings_enabled ON public.vision_agent_settings(enabled);

-- RLS Policies for vision_agent_settings
ALTER TABLE public.vision_agent_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own settings"
ON public.vision_agent_settings FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own settings"
ON public.vision_agent_settings FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own settings"
ON public.vision_agent_settings FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own settings"
ON public.vision_agent_settings FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- Table: vision_agent_signals
-- Purpose: Store all signals generated by the Vision Agent (for analytics and auditing)
CREATE TABLE IF NOT EXISTS public.vision_agent_signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  video_id UUID REFERENCES public.vision_agent_videos(id) ON DELETE CASCADE,
  signal_type TEXT CHECK (signal_type IN ('ENTER', 'EXIT', 'IGNORE')) NOT NULL,
  action TEXT CHECK (action IN ('LONG', 'SHORT')) DEFAULT 'LONG',
  confidence NUMERIC(4,3) NOT NULL,
  asset TEXT NOT NULL,
  entry_price NUMERIC(20,8),
  stop_loss NUMERIC(20,8),
  take_profit NUMERIC(20,8),
  risk_reward NUMERIC(5,2),
  frame_index INT,
  timestamp_in_video INT,
  features_summary JSONB DEFAULT '{}'::jsonb,
  model_version TEXT,
  executed BOOLEAN DEFAULT false,
  execution_status TEXT CHECK (execution_status IN ('pending', 'executed', 'rejected', 'failed')),
  execution_details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Indexes for vision_agent_signals
CREATE INDEX IF NOT EXISTS idx_vision_agent_signals_user_id ON public.vision_agent_signals(user_id);
CREATE INDEX IF NOT EXISTS idx_vision_agent_signals_video_id ON public.vision_agent_signals(video_id);
CREATE INDEX IF NOT EXISTS idx_vision_agent_signals_signal_type ON public.vision_agent_signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_vision_agent_signals_created_at ON public.vision_agent_signals(created_at DESC);

-- RLS Policies for vision_agent_signals
ALTER TABLE public.vision_agent_signals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own signals"
ON public.vision_agent_signals FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own signals"
ON public.vision_agent_signals FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Trigger: Update updated_at timestamp
CREATE OR REPLACE FUNCTION update_vision_agent_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_vision_agent_videos_updated_at
  BEFORE UPDATE ON public.vision_agent_videos
  FOR EACH ROW
  EXECUTE FUNCTION update_vision_agent_updated_at();

CREATE TRIGGER update_vision_agent_settings_updated_at
  BEFORE UPDATE ON public.vision_agent_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_vision_agent_updated_at();

-- Grant permissions
GRANT ALL ON public.vision_agent_videos TO authenticated;
GRANT ALL ON public.vision_agent_settings TO authenticated;
GRANT ALL ON public.vision_agent_signals TO authenticated;

-- Success message
COMMENT ON TABLE public.vision_agent_videos IS 'Tracks YouTube videos processed by Vision Trading Agent';
COMMENT ON TABLE public.vision_agent_settings IS 'User-specific configuration for Vision Trading Agent';
COMMENT ON TABLE public.vision_agent_signals IS 'All signals generated by Vision Trading Agent for analytics';
